app: serverless-first-functions
service: serverless-project-name

provider:
  name: aws
  runtime: nodejs18.x

functions: 
  create-user:
    handler: src/create-user.handler
    events: 
      - httpApi: 
          path: /users
          method: post

  fetch-users:
    handler: src/fetch-users.handler
    events: 
      - httpApi: 
          path: /users
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript
